# Generated by Django 5.0 on 2024-01-22 18:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_product_created_at_product_image_product_remarks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='star',
            field=models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
