# Generated by Django 5.0.1 on 2024-03-10 19:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_product_color_alter_product_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SearchKey', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProductScraped',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.DecimalField(decimal_places=0, max_digits=20, validators=[django.core.validators.MinValueValidator(1)])),
                ('website', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('url', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('color', models.CharField(default='', max_length=255)),
                ('size', models.CharField(default='', max_length=255)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(1)])),
                ('inventory', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('image', models.CharField(default='', max_length=255)),
                ('star', models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('remarks', models.CharField(max_length=5)),
                ('collection', models.CharField(max_length=255)),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.keys')),
            ],
        ),
    ]
