# Generated by Django 5.0.1 on 2024-03-13 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_keys_productscraped'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productscraped',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='productscraped',
            name='last_update',
            field=models.DateField(auto_now=True),
        ),
    ]
